##################
# BUILD STEP
##################
FROM ghcr.io/graalvm/native-image-community:22.0.2 as build

# MAVEN SETUP
RUN echo "######################"
RUN echo "MAVEN SETUP"
RUN echo "######################"

ARG MAVEN_VERSION=3.9.6
RUN curl -k -L -s -O https://repo1.maven.org/maven2/org/apache/maven/apache-maven/$MAVEN_VERSION/apache-maven-$MAVEN_VERSION-bin.tar.gz \
    && tar -xvzf apache-maven-$MAVEN_VERSION-bin.tar.gz \
    && mv apache-maven-$MAVEN_VERSION /opt/ \
    && rm apache-maven-$MAVEN_VERSION-bin.tar.gz
ENV MAVEN_HOME=/opt/apache-maven-$MAVEN_VERSION
ENV PATH=$MAVEN_HOME/bin:$PATH

# MUSL SETUP
RUN echo "######################"
RUN echo "MUSL SETUP"
RUN echo "######################"

RUN curl -k -L -s -O http://more.musl.cc/10/x86_64-linux-musl/x86_64-linux-musl-native.tgz && \
    tar -xvzf x86_64-linux-musl-native.tgz && \
    rm x86_64-linux-musl-native.tgz && \
    mv x86_64-linux-musl-native /opt/

ENV TOOLCHAIN_DIR=/opt/x86_64-linux-musl-native
ENV CC=$TOOLCHAIN_DIR/bin/gcc
ENV PATH=$TOOLCHAIN_DIR/bin:$PATH

# ZLIB SETUP
RUN echo "######################"
RUN echo "ZLIB SETUP"
RUN echo "######################"

RUN curl -k -L -s -O https://zlib.net/zlib-1.3.1.tar.gz && \
    tar -xvzf zlib-1.3.1.tar.gz && \
    rm zlib-1.3.1.tar.gz && \
    cd zlib-1.3.1 && \
    ./configure --prefix=$TOOLCHAIN_DIR --static && \
    make && \
    make install

# BUILD PROJECT
RUN echo "######################"
RUN echo "BUILD PROJECT"
RUN echo "######################"

COPY pom.xml .
RUN mvn -B dependency:go-offline
COPY src src
COPY lombok.config .
COPY Makefile .
RUN make build/graalvm

###################
## RELEASE STEP
###################
FROM alpine:3.20.3 as release
WORKDIR /app
COPY --from=build /app/target/*.graalvm ./app.graalvm
RUN adduser -D gina && chmod +x ./app.graalvm
USER gina
EXPOSE 8081
ENTRYPOINT ["/app/app.graalvm"]
