##################
# BUILD STEP
##################
FROM maven:3.9.9-eclipse-temurin-21-alpine as build

## Install cURL
RUN apk add --no-cache make

## Build project
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src src
COPY lombok.config .
COPY Makefile .
RUN make build/jvm

##################
# RELEASE STEP
##################
FROM maven:3.9.9-eclipse-temurin-21-alpine as release
WORKDIR /app
COPY docker_entrypoint.sh .
COPY --from=build /target/*.jar ./app.jar
RUN adduser -D gina && chmod +x ./docker_entrypoint.sh
USER gina
EXPOSE 8081
ENTRYPOINT ["/app/docker_entrypoint.sh"]
