# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Backend Pipeline for Pull Requests

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check if label 'run_tests' is present
      if: "!contains(github.event.pull_request.labels.*.name, 'run_tests')"
      uses: actions/github-script@v7.0.1
      with:
        script: |
          core.setFailed('Job fail, if you want to run test make sure to use run_tests label')
    - uses: actions/checkout@v4
      if: ${{ success() }}
    - name: Set up JDK 21
      if: ${{ success() }}
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'oracle'
        cache: maven
    - name: Build with Maven
      if: ${{ success() }}
      run: make tests
